dependencies:
  - python=3.10
  - pip:
      - azure-ai-ml
      - azureml-core
      - mltable
      - azureml-dataprep[pandas]
      - azureml-mlflow
      - mlflow
      - scikit-learn
      - pandas