channels:
- conda-forge
dependencies:
- python=3.12.2
- pip<=23.2.1
- pip:
  - mlflow==2.17.2
  - cloudpickle==2.2.1
  - numpy==2.1.3
  - pandas==2.2.3
  - psutil==6.1.0
  - scikit-learn==1.5.2
  - scipy==1.14.1
name: mlflow-env
